server:
  port: 8000
spring:
  application:
    name: order


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    disable-delta: true
    eureka-connection-idle-timeout-seconds: 30
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 8
    eureka-server-total-connections: 200
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
